version: '2'

services:
    scatchbling:
        image: nidarbox/php:7.0-cli
        container_name: scatchbling
        volumes:
            - ./:/app
        depends_on:
            - mysql
        ports:
            - 8080:8080
        links:
            - mysql
        command: php -S 0.0.0.0:8080 public/index.php
    mysql:
        image: nidarbox/mysql:5.7
        container_name: mysql-scatchbling
        ports:
          - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
volumes:
    mysql-data: