#%RAML 1.0
---
title: Scratcher API DEMO
baseUri: http://localhost:8080/{version}
version: v1
mediaType:  application/json
securitySchemes:
  token_authorization: ""

/authorization:
  description: |
    Authorization endpoint
  post:
    description: |
      Create a new token
    body:
      application/json:
        example: !include examples/authorization-req.json
    responses:
      201:
        description: |
          Successfully created a new token
        body:
          application/json:
            example: !include examples/authorization-res.json

/items:
  securedBy: [ token_authorization ]
  description: |
    Items resource
  get:
    headers:
      Authorization:
        description: Token authorization
        type: string
        required: true
    queryParameters:
      limit:
        description: "limit records"
      offset:
        description: "offset records"
    responses:
      200:
        body:
          application/json:
            example: !include examples/get-items-res.json
  post:
    description: |
      Creates a new scratcher item
    headers:
      Authorization:
        description: Token authorization
        type: string
        required: true
    body:
      application/json:
        example: !include examples/post-item-req.json

    responses:
      201:
        body:
          application/json:
            example: !include examples/item-res.json
      400:
        body:
          application/json:
            example: !include examples/400-res.json
  /{itemId}:
    securedBy: [ token_authorization ]
    get:
      description: |
        Get a item by ide
      headers:
        Authorization:
          description: Token authorization
          type: string
          required: true
      responses:
        200:
          body:
           application/json:
             example: !include examples/item-res.json
        404:
          body:
            application/json:
              example: !include examples/404-res.json
    put:
      description: |
        Update an item
      headers:
        Authorization:
          description: Token authorization
          type: string
          required: true
      body:
        application/json:
          example: !include examples/put-item.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/item-res.json
        400:
          body:
            application/json:
              example: !include examples/400-res.json
        404:
          body:
            application/json:
              example: !include examples/400-res.json
    delete:
      description: |
        Deletes an item
      headers:
        Authorization:
          description: Token authorization
          type: string
          required: true
      responses:
        204:
        404:
          body:
            application/json:
              example: !include examples/404-res.json